version: '3'

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: web-300621-nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
       - ./web:/var/www
       - ./data/logs:/var/log/nginx/
