version: '3'

networks:
  internal:

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: web-300621-nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
       - ./web:/var/www
       - ./data/logs:/var/log/nginx/
    depends_on:
      - php
      - db-krox
    networks:
      - internal
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: web-300621-php
    volumes:
      - ./web:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - internal
  db-krox:
    image: mysql:5.7
    container_name: web-300621-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
      --innodb_use_native_aio=0
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    # Задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    #image: phpmyadmin/phpmyadmin:5.1.1-fpm-alpine
    container_name: web-300621-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-krox
    depends_on:
      - db-krox
    #restart: always
    ports:
      - 8070:80
    networks:
      - internal



#  adminer:
#    image: adminer
#    container_name: web-300621-adminer-mysql
#    restart: always
#    ports:
#      - 7500:8080
#    networks:
#      - internal