version: '3'

networks:
  internal:

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: web-300621-nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
       - ./web:/var/www
       - ./data/logs:/var/log/nginx/
    depends_on:
      - php
    networks:
      - internal
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: web-300621-php
    volumes:
      - ./web:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - internal